# .github/workflows/basic-ci.yml
name: TMKOC CI/CD Demo

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  demo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt || echo "Skipping if no requirements"

      - name: Demo run
        run: |
          echo "Hello, TMKOC CI/CD is running!"
          python --version
